#!/usr/bin/env python3

from symphony_model_checker.symphony.DumpASTVisitor import DumpASTVisitor
from symphony_model_checker.h2py.h2py import h2py
from symphony_model_checker.compile import parse

import ast as past

import argparse


parser = argparse.ArgumentParser(description='Symphony to Python')
parser.add_argument('filename')
parser.add_argument('--verbose', action='store_true')


if __name__ == '__main__':
    args = parser.parse_args()
    
    symphony_ast = parse(args.filename)
    if args.verbose:
        print('Dumped Symphony AST:')
        dump = DumpASTVisitor(indent_unit=2)
        print(dump(symphony_ast))
        print()

    python_ast = h2py(symphony_ast)
    if args.verbose:
        print('Dumped Python AST:')
        print(past.dump(python_ast, indent=2))
        print()

    print(past.unparse(python_ast))
